deps:

all:

test:
	cargo test

build:
	cargo build --release --bin transcoder-test --features tokio-runtime

run:
	cargo run --release --bin transcoder-test --features tokio-runtime

clean:
	cargo clean
