TARGET := "riscv32imac-unknown-none-elf"
PROFILE := "release"
TARGET_DIR := "target/" + TARGET + "/" + PROFILE

build-web:
	cd ../web && just all

copy-assets:
  rm -fr public/*
  cp -r ../web/dist/public/* public/
  find public/ -path 'public/.*' -prune -o -type f ! -name '*.gz' -print -exec gzip -9 {} \;

deps: build-web copy-assets

[arg("pinout", long)]
[arg("log", long)]
all pinout="pcb" log="info": deps
	@just build --pinout {{pinout}} --log {{log}}

[arg("pinout", long)]
[arg("log", long)]
all-nodeps pinout="pcb" log="info":
	@just build --pinout {{pinout}} --log {{log}}

[arg("pinout", long)]
[arg("log", long)]
build pinout="pcb" log="info":
	DEFMT_LOG=firmware={{log}},info cargo build --release --no-default-features --features pinout_{{pinout}}

flash:
	espflash flash --chip esp32c6 {{TARGET_DIR}}/firmware

run: flash
	espflash monitor --chip esp32c6 --log-format defmt --elf {{TARGET_DIR}}/firmware

monitor:
	espflash monitor --chip esp32c6 --log-format defmt --elf {{TARGET_DIR}}/firmware

clean:
  cargo clean
  rm -fr public/*
